language: node_js

node_js:
  - "stable"

install:
  - npm install

cache:
  directories:
    - "node_modules"  

after_success:
  - npm run coveralls
  - npm run coverage
  - npm run report-coverage
  - npm run codeclimate-report


