language: node_js

node_js:
  - "stable"

install:
  - npm install

cache:
  directories:
    - "node_modules"  

after_success:
  - npm run coveralls

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres  


